carpetas = {
 'Anillo_boda_hombre': 0,
 'Anillo_boda_hombre ': 1,
 'Anillo_boda_mujer ': 2,
 'Anillo_compromiso_mujer': 3,
 'Anillo_compromiso_mujer ': 4,
 'Anillos_femeninos ': 5,
 'Anillos_masculinos ': 6,
 'Anillos_quinceñeras ': 7,
 'Collar_colgante_femenino ': 8
}



categorias = {'Anillo de boda': 0,
 'Anillo de compromiso': 1,
 'Anillo': 2,
 'Collar con colgante': 3,
 'Collar de perlas': 4,
 'Gargantillas femeninas': 5,
 'Pulsera masculina': 6,
 'Reloj masculino': 7}


SubCarpeta = {
 'Anillo_boda_hombre / A': 0,
 'Anillo_boda_hombre / B': 1,
 'Anillo_boda_hombre / C': 2,
 'Anillo_boda_hombre / D': 3,
 'Anillo_boda_mujer  / A': 4,
 'Anillo_boda_mujer  / B': 5,
 'Anillo_compromiso_mujer / A': 6,
 'Anillo_compromiso_mujer / B': 7,
 'Anillo_compromiso_mujer / C': 8,
 'Anillo_compromiso_mujer / D': 9,
 'Anillos_femeninos / A': 10,
 'Anillos_femeninos / B': 11,
 'Anillos_masculinos / A': 12,
 'Anillos_masculinos / B': 13,
 'Anillos_masculinos / C': 14,
 'Anillos_quinceñeras / A': 15,
 'Anillos_quinceñeras / B': 16,
 'Anillos_quinceñeras / C': 17,
 'Anillos_quinceñeras / D': 18,
 'Collar_colgante_femenino / A': 19,
 'Collar_colgante_femenino / B': 20,
 'Collar_colgante_femenino / C': 21,
 'Collar_colgante_femenino / D': 22,
 'Collar_colgante_femenino / E': 23,
 'Collar_perlas_femenino / A': 24,
 'Collar_perlas_femenino / B': 25,
 'Collar_perlas_femenino / C': 26,
 'Collar_perlas_femenino / D': 27,
 'Collar_perlas_femenino / E': 28,
 'Gargantillas_femeninas / A': 29,
 'Gargantillas_femeninas / B': 30,
 'Pulsera_masculina / A': 31,
 'Pulsera_masculina / B': 32,
 'Pulsera_masculina / C': 33,
 'Pulsera_masculina / D': 34,
 'Reloj_masculino / A': 35,
 'Reloj_masculino / B': 36,
 'Reloj_masculino / C': 37,
 'Reloj_masculino / D': 38
 }

subCarpetaHombre= {
    'Anillo_boda_hombre / A': 0,
 'Anillo_boda_hombre / B': 1,
 'Anillo_boda_hombre / C': 2,
 'Anillo_boda_hombre / D': 3,
 'Anillos_masculinos / A': 4,
 'Anillos_masculinos / B': 5,
 'Anillos_masculinos / C': 6,
 'pulsera_masculina / A': 7,
 'pulsera_masculina / B': 8,
 'pulsera_masculina / C': 9,
 'pulsera_masculina / D': 10,
 'reloj_masculino / A': 11,
 'reloj_masculino / B': 12,
 'reloj_masculino / C': 13,
 'reloj_masculino / D': 14}


subCarpetaMujer= {'Anillo_boda_mujer  / A': 0,
 'Anillo_boda_mujer  / B': 1,
 'Anillo_compromiso_mujer / A': 2,
 'Anillo_compromiso_mujer / B': 3,
 'Anillo_compromiso_mujer / C': 4,
 'Anillo_compromiso_mujer / D': 5,
 'Anillos_femeninos / A': 6,
 'Anillos_femeninos / B': 7,
 'Anillos_quinceañeras / A': 8,
 'Anillos_quinceañeras / B': 9,
 'Anillos_quinceañeras / C': 10,
 'Anillos_quinceañeras / D': 11,
 'Collar_colgante_femenino / A': 12,
 'Collar_colgante_femenino / B': 13,
 'Collar_colgante_femenino / C': 14,
 'Collar_colgante_femenino / D': 15,
 'Collar_colgante_femenino / E': 16,
 'Collar_perlas_femenino / A': 17,
 'Collar_perlas_femenino / B': 18,
 'Collar_perlas_femenino / C': 19,
 'Collar_perlas_femenino / D': 20,
 'Collar_perlas_femenino / E': 21,
 'Gargantillas_femeninas / A': 22,
 'Gargantillas_femeninas / B': 23}